### ISSUE TITLE
Result ("entry-content" GSetting) should follow system-wide History setting

### ISSUE THREAD

**Issue by 4jNsY6fCVqZv** [elementary/calculator#110]
At the moment it looks like that at least the calculation result of the last mathematical operation remains in the memory of the app and is visible again after a restart of the app.
How can the issue be solved?

**Comment by fluks** [comment]
This can be fixed, if wanted, by deleting `entry-content` related lines.

https://github.com/elementary/calculator/blob/54431dcac8ae7c81e50742d8c0322823c60fc3a2/data/io.elementary.calculator.gschema.xml#L9-L13
https://github.com/elementary/calculator/blob/b7ca2897845cd21c510e56620d5bff109be9c1ef/src/MainWindow.vala#L101
https://github.com/elementary/calculator/blob/b7ca2897845cd21c510e56620d5bff109be9c1ef/src/MainWindow.vala#L486

Or you can manually reset it always after calculator exits, by adding `gsettings set io.elementary.calculator.saved-state entry-content ""` to calculator's .desktop file, for example.

**Comment by 4jNsY6fCVqZv** [comment]
Hello, thank you so much for looking for a solution! It looks more like a workaround to me as it is not an understandable solution for non-technical standard users. It needs a graphical solution via the app interface. What do you think?

**Comment by fluks** [comment]
The obvious solution I missed, is to remember to clear (by pressing C) or by deleting the result before you quit the app.

**Comment by 4jNsY6fCVqZv** [comment]
Calculator should respect the global history settings like other apps as well.
Comparable to elementary/files#822
Is that something you want to work on?

**Comment by fluks** [comment]
I would like to wait for developers what they think that should be done. Then I can perhaps work on it.

**Comment by 4jNsY6fCVqZv** [comment]
Okay, that sounds good. I'm curious what the developers will say!

**Comment by 4jNsY6fCVqZv** [comment]
@fluks Now that the issue has been confirmed, could you imagine working on a solution?

**Comment by fluks** [comment]
> @fluks Now that the issue has been confirmed, could you imagine to work on a solution?

Yes, I think I can! :laughing:  I don't remember anything about this, so I need to research again first.

**Comment by fluks** [comment]
How can you read if an app is set not to collect data in the history settings? I set Calculator to not collect data and tried to find it using ```gsettings --list-recursively | grep -i calculator```, but I didn't find such a setting. Where the apps are saved?

**Comment by fluks** [comment]
I created a PR as a starter.

**Comment by ryonakano** [comment]
Fixes in #130. @fluks Thank you for your investigation!
