### ISSUE TITLE
Percent opperations issue

### ISSUE THREAD

**Issue by JoelBonetR** [elementary/calculator#123]
The default calc on Elementary OS 5.1.3 fails performing sum and subtract operations.

Examples i tried: 
1-  200-10%
Instead 180 i'm getting 199.9
2-  200+25%
I'm getting 200.25 instead 250.00
3- 200/25% -> It's ok, the result was 800 as expected.
4- 200*25% -> It's ok, the result was 50 as expected.

**Comment by danrabbit** [comment]
Duplicate of #44
