### ISSUE TITLE
Calculator returns floating point values even for simple powers-of-ten division

### ISSUE THREAD

**Issue by Marie-Joseph** [elementary/calculator#125]
For example, 4,294,967,296 / 100 returns 42,949,672.960000001 instead of 42,949,672.96

**Comment by Marie-Joseph** [comment]
Update: I realized I didn't check this with other values. This appears to be a big numbers problem.

**Comment by fabiozaramella** [comment]
> Update: I realized I didn't check this with other values. This appears to be a big numbers problem.

Closing as it appears to be a duplicate of #46
