### ISSUE TITLE
The calculator apps is not working correctly. EOS 5.1.4

### ISSUE THREAD

**Issue by Artist6481** [elementary/calculator#132]
When subtracting percent of an integer, the answer is incorrect.
100−10% = 99,9

**Comment by lewisgoddard** [comment]
Duplicate of #44

**Comment by Exalm** [comment]
But that's the correct answer? 10% == 0.01, 100 - 0.01 = 99.9

**Comment by parnold-x** [comment]
> But that's the correct answer? 10% == 0.01, 100 - 0.01 = 99.9

Nope, 10% is 0.1

**Comment by Exalm** [comment]
Oops 🤦️ And made the same typo 2 times even. But you get the idea, 99.9 is the expected answer.
