### ISSUE TITLE
Incorrect values are returned for "-.NNN" vs "-0.NNN"

### ISSUE THREAD

**Issue by Ky-Fi** [elementary/calculator#153]
## What Happened

Not putting a zero in front of negative decimal values causes the calculator to return incorrect results:
`-.25^2` returns `16` (incorrect) but `-0.25^2` returns `0.0625` (correct)
`-.25*.25` returns `0.0625` (should be negative) but `-0.25*0.25` returns `-0.0625`

This behavior is consistent for all negative decimal values I tested.

## Expected Behavior

Negative decimal values should not return different results if they don't have a leading zero.

## Platform Information

```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	elementary
Description:	elementary OS 5.1.7 Hera
Release:	5.1.7
Codename:	hera
```

**Comment by jeremypw** [comment]
I cannot reproduce this with the master branch so it appears to have been fixed since the last stable release - although it is not clear which commit did it.

**Comment by jeremypw** [comment]
Looks like `-.25^2` is being parsed as `-.25^-2` and `-.25*.25` as `-.25*-.25` :confused:
