### ISSUE TITLE
History dialogue window is grabbable from the top even though there is not titlebar.

### ISSUE THREAD

**Issue by Blast-City** [elementary/calculator#159]
## What Happened
History dialogue window is grabbable from the top even though there is not titlebar.

## Expected Behavior
Either:
A. It shouldn't be possible to move the dialogue windows when a left click is pressed on top of the window.
B. All the dialogue window area should be grabbable.

## Steps to Reproduce
1- Do a calculation.
2- Press the history button.
3- Left click on the top of the dialogue window and move the mouse.

## Platform Information
elementary OS 5.0 Hera.

**Comment by janxkoci** [comment]
And why is that a problem? It is consistent with other such dialogs in the system (e.g. the progress dialog when you copy/move files in Files).

**Comment by Marukesu** [comment]
I believe the issue here was that the history dialog wasn't draggable from any place of the window (technically speaking, it wasn't using a [Gtk|Hdy].WindowHandle). That shouldn't be the case since the Gtk4 port, so i'm closing it.
