### ISSUE TITLE
Trying to write values with E operator for negative exponents doesn't work 

### ISSUE THREAD

**Issue by rafaelcn** [elementary/calculator#16]
If you try to write expressions with the E operator that has a negative exponent Calculator the result becomes the value of the exponent.

Reproducing this bug:

1. Simply write: `14E-2`
2. The result would have to be: `0,14` but it is actually `-2`

I thought of encapsulating the `-2` in parenthesis but it didn't work either:

1. Write: `14E(-2)`
2. The result is `0` for any given exponent in this form.

The Shunting Yard algorithm is failing to recognize a negative exponent after the E symbol.

**Comment by DDieter** [comment]
Fixed in #38.
