### ISSUE TITLE
Incorrect multiple bind instances

### ISSUE THREAD

**Issue by alejosv** [elementary/calculator#165]
## What Happened
Several instances of the calculator are linked incorrectly, causing a value of one of the instances to be replicated in the others.

## Expected Behavior
Instances should not be linked, each should work independently.

## Steps to Reproduce

1. Launch multiple calculators
2. Enter any number in one of the instances
3. In the other instances the number must be replicated.

## Platform Information
Distributor ID:	elementary
Description:	elementary OS 5.1.7 Hera
Release:	5.1.7
Codename:	hera

Linux 5.4.0-66-generic #74~18.04.2-Ubuntu SMP Fri Feb 5 11:17:31 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

## Video as evidence

https://user-images.githubusercontent.com/14202497/110167457-61513380-7dbb-11eb-8f1e-75fd7bda77df.mp4

**Comment by jeremypw** [comment]
This is a consequence to there being a single "entry-contents" setting which is bound to all instances so that it gets restored on reopening the calculator. Probably need to only bind the first window and forgo remembering the contents of subsequent windows.

**Comment by jeremypw** [comment]
Are you still running Hera? This issue was fixed in Odin but not back-ported.

**Comment by alejosv** [comment]
Yes, I still have Hera. I think that if to fix a bug it is necessary upgrade a OS something is not right. I understand this issues is not critical, but it would be nice if they support older versions for a while.
