### ISSUE TITLE
The "Suggest Translation" button is pointing to the wrong link

### ISSUE THREAD

**Issue by GabrielMGitHub** [elementary/calculator#17]
The "Suggest Translation" button is pointing to the wrong link. This error has several applications.
https://translations.launchpad.net/pantheon-calculator

![captura de tela de 2017-05-27 14-24-38](https://cloud.githubusercontent.com/assets/8754997/26523176/4919458a-42e8-11e7-88d1-e92e9ef763eb.png)

**Comment by leonardo-lemos** [comment]
Solved in #14
