### ISSUE TITLE
Provide obvious way to open new instance of Calculator

### ISSUE THREAD

**Issue by abodedis** [elementary/calculator#193]
## Problem

There is no obvious way to open multiple instances of the calculator.

## Proposal

Provide an obvious way (button, menu option, etc) to open multiple instances of the calculator.

For example:
- a menu option "New Calculator"
- a button or icon representing a [New Calculator]
- right clicking on calculator in the Dock -> "New Calculator"
- right clicking on the title bar of the calculator -> "New Calculator"

**Comment by ryonakano** [comment]
A quick solution:

![2021-08-20 21 35 02 の画面録画](https://user-images.githubusercontent.com/26003928/130233963-adecbc1f-8d42-491f-983e-e5b06acad671.gif)

**Comment by jeremypw** [comment]
@elementary/ux What is your preferred way of providing this?

**Comment by rakshit087** [comment]
I think we can close this issue now since #207 is merged.
