### ISSUE TITLE
Calculator keyboard shortcut

### ISSUE THREAD

**Issue by Arnwaltur** [elementary/calculator#200]
## What Happened
Keyboard calculator shortcut no longer works with eOS 6 Odin.

## Expected Behavior
Calculator application launch when hit specific key.

## Steps to Reproduce
eOS 6 Odin up to date + Logitech MX Keys.

1. Hit calculator key on keyboard.

### Logs

With : **sudo watch tail /var/log/syslog**
I can see that when I hit calculator key, system failed to launch **org.gnome.Calculator.desktop**

## Platform Information

eOS 6 Odin
Calculator app from installation. Up to date from AppCenter.

**Comment by jeremypw** [comment]
I do not think this issue belongs here since Calculator cannot detect a key press if it is not running.  Probably belongs in "switchboard-plug-keyboard" or maybe "gala" projects. I do not have a special "Calculator key" but presumably it generates `Gdk.Key.Calculator`.  You may be able to set up a custom shortcut in "System Settings/Keyboard/Shortcuts" meanwhile.

I don't see why the Calculator should not be in the "Applications" category of that plug if there is a special key for it.

**Comment by jhaygood86** [comment]
This looks like it's hardcoded into gnome-settings-daemon:

https://github.com/GNOME/gnome-settings-daemon/blob/f4dbcf3d7b0f951fe44b29229206c97b625dbfda/plugins/media-keys/gsd-media-keys-manager.c#L2721

**Comment by Arnwaltur** [comment]
Thank you for your research, I will report the issue on official Stack Exchange page.

**Comment by macmpi** [comment]
indeed:
`gsd-media-keys[3030]: Could not find application 'org.gnome.Calculator.desktop' or 'gnome-calculator_gnome-calculator.desktop'`

A simple workaround trick though:
(Temporarly) install gnome calc with flatpak (this will give us a working `.desktop` file template to work from):
`flatpak install flathub org.gnome.Calculator` (and check the key invocation works)

Then use an app like [`Pins`](https://flathub.org/apps/io.github.fabrialberio.pinapp) from flatpak to modify `exec` line from` .desktop` file (it will save it in your user's path `$HOME/.local/share/applications/org.gnome.Calculator.desktop`), or manually edit that file (and save it likewise):
modify `exec` statement as follows to use elementary's default calc for exemple: 
`/usr/bin/flatpak run --branch=stable --arch=x86_64 --command=io.elementary.calculator io.elementary.calculator`
(further customization may be done to this file, like icon reference, etc...)
Then remove gnome calc if no interest:
`flatpak remove org.gnome.Calculator`

System will still see your copy of `.desktop` file from:
`$HOME/.local/share/applications/org.gnome.Calculator.desktop`
and it will be called by keyboard key!
(file may be moved to other location for all users access)
