### ISSUE TITLE
No accent highlights when using the numpad

### ISSUE THREAD

**Issue by mathessaricci** [elementary/calculator#220]
### Problem

When I type numbers using my keyboard's numpad there's no highlights on buttons.

### Proposal

Use the same behavior when I click on it.

### Prior Art (Optional)

There's no prior art. But I recommend some steps to reproduce this issue.

1) Open calculator;
2) Press 1, 2 and 3 using the touchpad or mouse;
3) Press the same numbers on the keyboard.

**Comment by danirabbit** [comment]
I'm not sure that this necessarily makes sense. You already get feedback in the text entry when typing so I don't think activating buttons would really add value for the complexity and fragility it would add to the code base.
