### ISSUE TITLE
can't calculate n!

### ISSUE THREAD

**Issue by Nine-H** [elementary/calculator#23]
I kept needing factorials for my algorithms course, mostly to discuss problems with enumeration and combinatorics.

**Comment by cassidyjames** [comment]
I think you might be better served by [NaSC](http://appcenter.elementary.io/com.github.parnold-x.nasc), available in AppCenter. The included calculator is intended to be very simple but NaSC has a **huge** array of advanced features.

**Comment by Nine-H** [comment]
nasc was pretty bad in 2016, it's gotten better. keeping it. thanks.

**Comment by fabiozaramella** [comment]
I'm closing this since it seems to be out of the scope of a simple calculator but feel free to reopen in case the feature is requested again (it doesn't seems to have gained attraction in the last 4 years so...).
