### ISSUE TITLE
There is an empty space

### ISSUE THREAD

**Issue by seriousfreezing** [elementary/calculator#236]
### What Happened?

I downloaded the version from the official Arch repository and when using it I notice that there is an empty space in the calculator's simple mode, is that normal?
![image](https://user-images.githubusercontent.com/66693072/210231779-3c8fe7bb-b00d-4886-9c83-a9ebbeca2e8e.png)

### Steps to Reproduce

1. Download from Pamac.
2. Run the calculator
3. Done.

### Expected Behavior

![image](https://user-images.githubusercontent.com/66693072/210231926-35668f60-d0e0-4a94-b761-f0cc2b16b67d.png)
I was hoping it would be like this, if this empty space, you know?

### OS Version

Other Linux

### Software Version

Latest release (I have run all updates)

**Comment by jeremypw** [comment]
This does not happen with the current stable Flatpak release on Elementary (and the icons look different). Is your install Flatpak or native?  Might be a window manager issue.

**Comment by seriousfreezing** [comment]
I downloaded and installed the version from the Arch repository, I will try to use the Flatpak version!

**Comment by seriousfreezing** [comment]
I just realized that there is no flatpak version on the internet.

**Comment by meisenzahl** [comment]
You can download Calculator as a Flatpak from https://appcenter.elementary.io/io.elementary.calculator/.

**Comment by seriousfreezing** [comment]
![image](https://user-images.githubusercontent.com/66693072/210275454-f27ce7cc-c253-491c-aedf-045e46d99265.png)

**Comment by Marukesu** [comment]
This is an issue with the decoration layout, if you change the layout to the close and minimize begin on the left side, there's no empty space, otherwise the window is extended to accomodate for the buttons on the right side.

**Comment by jeremypw** [comment]
I guess the problem is that the title is forced to be in the centre of the window. Maybe the buttons should move depending on where the decorations are?

**Comment by jeremypw** [comment]
Or just have no title - like other elementary apps.

**Comment by seriousfreezing** [comment]
OMG, THE FOUNDER HERSELF! I am immensely grateful!
