### ISSUE TITLE
headerbar does not respect My themes

### ISSUE THREAD

**Issue by BAProductions** [elementary/calculator#241]
### What Happened?

If I open the eOS7 Calculator built in to System the header bar does not respect My themes, But now if I build eOS7 from source the header bar does respect My themes WTH going on.

eOS7 System Calculator from flathub 
<img width="361" alt="Screenshot 2023-03-06 at 10 29 42 AM" src="https://user-images.githubusercontent.com/2386630/223160182-677df3e5-0429-4ca4-b1bc-e834ca3f9c05.png">

eOS7 System Calculator built from source
<img width="362" alt="Screenshot 2023-03-06 at 10 30 16 AM" src="https://user-images.githubusercontent.com/2386630/223160184-143e3170-f221-498b-b011-d3670bc0ec1f.png">

### Steps to Reproduce

Switch to custom theme & Launch eOS7 System Calculator via app menu or dock & header bar does not match custom theme.

Build System Calculator built from source & typed io.elementary.calculator in terminal & now the header bar match custom theme 

### Expected Behavior

Switch to custom theme & Launch eOS7 System Calculator via app menu or dock & header bar should match custom theme.

### OS Version

7.x (Horus)

### Software Version

Latest release (I have run all updates)

**Comment by lenemter** [comment]
This was done intentionally in #238 because elementary OS apps are not intended for use with other stylesheets. Closing as design conflict.

**Comment by BAProductions** [comment]
> This was done intentionally in #238 because elementary OS apps are not intended for use with other stylesheets. Closing as design conflict.

The upper screenshot is using the Arc Dark theme by default

**Comment by tintou** [comment]
@BAProductions this is an issue with the Arc Dark theme, please ask them to provide a flatpak extension for their theme.
Please keep in mind that such changes are completely unsupported by elementary so you are on your own when changing from the default configuration.
