### ISSUE TITLE
Multiply any number by any negative number results in the negative number itself

### ISSUE THREAD

**Issue by lucraraujo** [elementary/calculator#37]
Tests cases:

 Factor A | Factor B | Multiplication result | Expected result 
----------- | ---------- | ------------------------- |  -------------------
5 | -1 | -1 | -5
5 | -2 | -2 | -10
-5 | -1 | -1 | 5
-5 | -2 | -2 | 10

**Comment by artemanufrij** [comment]
I confirm:

5 × (−1) = 0

**Comment by lucraraujo** [comment]
@artemanufrij Oh yes! I forgot the parentheses cases!

**Comment by artemanufrij** [comment]
after `make`
run
`./io.elementary.calculator`

**Comment by lucraraujo** [comment]
This is what happens after I run `./io.elementary.calculator`

```
[INFO 11:48:58.640905] Application.vala:153: Calculator version: 0.1.3
[INFO 11:48:58.640953] Application.vala:155: Kernel version: 4.10.0-33-generic
[ERROR 11:48:58.687041] [GLib-GIO] Settings schema 'io.elementary.calculator.saved-state' is not installed
[1]    13370 trace trap (core dumped)  ./io.elementary.calculator
```

**Comment by Philip-Scott** [comment]
@lucraraujo You have to `sudo make install` as well since the settings schema for `io.elementary.calculator` is not currently installed :)
