### ISSUE TITLE
Latest daily package doesn't have a desktop file and can't run it from terminal

### ISSUE THREAD

**Issue by worldofpeace** [elementary/calculator#40]
OS: elementary os
Source of package: Daily PPA
Package Version Affected: pantheon-calculator_0.1.3+r376+pkg15~daily~ubuntu0.4.1.1

## Issue
Read the title.
I don't think it's running any dpkgtriggers. I don't see it in the output when I install it with dpkg.

**Comment by codygarver** [comment]
Fixed yesterday.
