### ISSUE TITLE
Multiplying by 3 digit number gives invalid results

### ISSUE THREAD

**Issue by donadigo** [elementary/calculator#48]
Multiplying by 2-3 digit numbers gives invalid results:

89*56 = 4
3 * 898 = 2
13 * 98 = 1
13 * 989 = 12

**Comment by danrabbit** [comment]
![screenshot from 2018-01-19 17 20 10](https://user-images.githubusercontent.com/7277719/35178371-0a1a41d0-fd3d-11e7-9450-aa9794f173b8.png)

These all work for me on Juno in English. My guess is this has something to do with separators in your locale and it's rounding off everything after the , for some reason
