### ISSUE TITLE
No keywords in desktop file

### ISSUE THREAD

**Issue by jendamarek** [elementary/calculator#61]
The desktop file doesn't include keywords.
In my country people are used to search for calculator (in Windows) with a keyword "calc". In elementary when the name is translated to a local word (Kalkulačka) you can't use the original title to search for the app. Including keywords in desktop file would solve this.

**Comment by jlnr** [comment]
I think the more scalable solution would be to consider the English name in Wingpanel, even on non-English systems. I always search for "screenshot" until I realize I have to search for the German "Bildschirmfoto" instead.

I'm coming from macOS and Spotlight apparently does this; you can look for "Disk Utility" even when it's called "Festplattendienstprogramm" in German.

**Comment by ryonakano** [comment]
Fixed in #89. Thank you for your works @BharatKalluri & @JackKenney!
