### ISSUE TITLE
App's name and comment in menu stays in English

### ISSUE THREAD

**Issue by welaq** [elementary/calculator#73]
While the interface is translated. This is on Juno Beta.

**Comment by leonardo-lemos** [comment]
I can't confirm this issue, in which language are you running your system?

**Comment by welaq** [comment]
In Lithuanian (lt). I don't know, maybe translations haven't synced yet.

**Comment by danrabbit** [comment]
Should be fixed in 708ca4e47013aa2d022686cbb48dc51e4c9694cb
