### ISSUE TITLE
App's name is not translated

### ISSUE THREAD

**Issue by welaq** [elementary/calculator#82]
On Juno beta 2.
When I open Applications menu neither Calculator name, nor app's comment is not localized. All other apps (Videos, Screenshot) are OK. I'm using system in Lithuanian, strings are translated long time ago.

**Comment by ryonakano** [comment]
@welaq Could you check whether this issue still happens? I can't confirm this issue on elementary OS Juno with fully updated in a virtual machine:

![VirtualBox_elementary OS_09_08_2019_23_20_32](https://user-images.githubusercontent.com/26003928/62785806-527d9e80-bafc-11e9-8ef1-a97b63935dc7.png)

**Comment by welaq** [comment]
Hi, I'm at the moment on the journey and will be back home only in a month. I'll let you know when I get to computer.

**Comment by danrabbit** [comment]
Closing as "Incomplete". We can reopen the issue if it's able to be confirmed

**Comment by welaq** [comment]
Just for the record, it looks like the issue is gone.
