### ISSUE TITLE
Wrong decimal separator on numeric keypad

### ISSUE THREAD

**Issue by wout** [elementary/calculator#88]
The default elementary OS calculator uses the wrong decimal separator when using the numeric keypad. It uses a `.` instead of a `,`:

![image](https://user-images.githubusercontent.com/107324/47613612-f678ea80-da92-11e8-8157-64f84c2c452f.png)

The GNOME calculator works as it should:

![image](https://user-images.githubusercontent.com/107324/47613639-65564380-da93-11e8-8ed7-1a3d443a9b65.png)

**Comment by wout** [comment]
This issue still persists. Is it supposed to be fixed?

**Comment by ryonakano** [comment]
@wout A new release of Calculator which includes the fix for this issue has not been released yet, so the issue still persists on the latest Juno.

**Comment by jlnr** [comment]
And I think some work is underway to simplify the release process, so in the future simple fixes hopefully shouldn't be stuck for 2 months :sweat_smile:
