### ISSUE TITLE
No keyboard focus on start

### ISSUE THREAD

**Issue by kbondarev** [elementary/calculator#91]
When the app is being opened it does not receive "focus", meaning if I start typing it doesn't get my input until I click the window with the mouse pointer.
This is very inconvenient as when I need to do a quick calculations I am opening the app through keyboard only (Super + space, type "calc", press enter) and expect to continue typing my calculations.

**Comment by peteruithoven** [comment]
Thanks for the report! I'm afraid this is a duplicate of https://github.com/elementary/applications-menu/issues/19
