### ISSUE TITLE
Adding flatpak manifest to calculator

### ISSUE THREAD

**Issue by BharatKalluri** [elementary/calculator#99]
Hi,

I personally think that having a flatpak manifest will help kick-start the development very fast (Especially in builder). I have a flatpak manifest ready, if you think this is a worthwhile addition. I will make a PR adding it.

Thanks!

**Comment by tintou** [comment]
Feel free opening a PR, even if we will probably revisit the manifest with the elementary runtime it's still a first step :slightly_smiling_face:

**Comment by BharatKalluri** [comment]
Created  a PR over at #101 , let me know what you think!
